### ISSUE TITLE
programs scenes souliss app

### ISSUE THREAD

**Issue by tandy1** [souliss/soulissapp#141]
I'm using Soulissapp now for a while, but some instructions doesn't work and others are rather limited.
Programs : 
1. I receive the feedback when a program takes some action, but there is no action on the output. f.e. When I say to put a light on, I receive the message that the light is activated, but the light stays OFF.
2. Should it be possible to modify the timed action so that this function can be used to make a eek program ? 
3. Couldn't find how to set a temperature for the thermostat.
Scenes :
1. Scenes seems limited to 8 typicals. When you more than 8, the first action is repeated.
2. Could it be possible to select also programs in a scene ?

I'm using : arduino IDE 1.6.5, Souliss V7.1, Soulissapp 1.8.3

**Comment by plinioseniore** [comment]
You should use the integration with Automate or Tasker to have more
flexibility.

Dario.

**Comment by ghost** [comment]
Dario,
Please don't see my comments as remarks. It is only a feedback to improve the Souliss system after using it for a while.
My choice for Souliss is based on following strong points of the system :+1: 
 - intelligent front ends who can work stand alone.
- redundancy with the network by using a backup gateway.
- no central server needed
- users friendly APP. User need no knowledge of software to configurate the app.

When you need to use a second app, like Automate or Tasker, you are loosing the last benefit of the system.

**Comment by plinioseniore** [comment]
Your comments are appreciated and I mostly agree with you, but IfThenElse
app are really complex piece of software and we have decided to integrated
with those defacto standard for such task instead of rebuild the whole from
scratch.

SoulissApp hasn't a big enough audience to justify a such big effort.

**Comment by shineangelic** [comment]
1. I receive the feedback when a program takes some action, but there is no action on the output. f.e. When I say to put a light on, I receive the message that the light is activated, but the light stays OFF.

This is because we're on UDP I guess. Have you tried incrementing the scenario's command delay (in the app)? If manual commands work, scenes **must work as well**

2. Should it be possible to modify the timed action so that this function can be used to make a eek program ? 

Couldn't get you. What does 'eek' programs mean? Could you elaborate pls?

3. Couldn't find how to set a temperature for the thermostat.

well, T51 has a long and sad history. Anyway, the setpoint should be working... @fazioa what do you say? I'm sorry I currently don't have a T51 for testing

Scenes :
1. Scenes seems limited to 8 typicals. When you more than 8, the first action is repeated.

Really? well, I think this is a bug, I'll check in the code 

2. Could it be possible to select also programs in a scene ?

No, the two things are separated. A scene is a plain list of commands executed in sequence, while a program is a command triggered by some action/value/movement. The **opposite is possible tho**, meaning that, as a program's target, you may specify a scene so that a list of commands is executed when something happens
