### ISSUE TITLE
Compile on Android Studio

### ISSUE THREAD

**Issue by Darkete** [souliss/soulissapp#160]
Hey guys, i need help with SoulissApp, because when i try to compile it gives me the error 
"Error:(265, 45) No resource found that matches the given name (at 'colorSeeds' with value '@array/t16_color_slider')."
The line is app:colorSeeds="@array/t16_color_slider"

I'm really new with these things, and i searched on google but nothing.

**Comment by shineangelic** [comment]
compile 'com.github.rtugeek:ColorSeekBar:1.2.2'

this line in gradle files should import the lib needed for that 'colorSeeds' in the project.

What IDE are you using? How are you trying to compile?

**Comment by shineangelic** [comment]
well, going deeper, **I had your same error** changing from:

compile 'com.github.rtugeek:ColorSeekBar:1.2.2'

to:

compile 'com.github.rtugeek:ColorSeekBar:1.4.3'

So I guess you're not resolving/reaching Color Seek Bar library. Since nothing in code is changed (color seek bar library manages the T16 patterns), i opened this:

https://github.com/rtugeek/ColorSeekBar/issues/16

BTW previous version (1.4.2) compiles but gives me the reported error at runtime

**Comment by shineangelic** [comment]
@Darkete could you work it around? can you compile soulissApp?
