### ISSUE TITLE
Empty nodes rebuilding the DB

### ISSUE THREAD

**Issue by ribico** [souliss/soulissapp#78]
Ciao Pex,
i noticed that SApp easily creates the DB with few nodes but not the same when nodes number is high (>10 nodes).

In my particular case I have static adresses and static routing tables defined in the GW sketch as follow:

```
    // LIST OF NODES
    SetAsPeerNode(IP_ADDRESS_ROW1B1,1);
    SetAsPeerNode(RS485_ADDRESS_ROW1B2,2);
    SetAsPeerNode(RS485_ADDRESS_ROW1B3,3);
    SetAsPeerNode(RS485_ADDRESS_ROW1B4,4);

    SetAsPeerNode(IP_ADDRESS_ROW2B1,5);
    SetAsPeerNode(RS485_ADDRESS_ROW2B2,6);
    SetAsPeerNode(RS485_ADDRESS_ROW2B3,7);
    SetAsPeerNode(RS485_ADDRESS_ROW2B4,8);

    SetAsPeerNode(IP_ADDRESS_BED1B1,9);

    SetAsPeerNode(IP_ADDRESS_BED2B1,10);
    SetAsPeerNode(RS485_ADDRESS_BED2B2,11);
    SetAsPeerNode(RS485_ADDRESS_BED2B3,12);

    SetAsPeerNode(RS485_ADDRESS_GTW1B1,13);
    SetAsPeerNode(RS485_ADDRESS_GTW2B1,14);

    // define static routing table (NOT STRICTLY NEEDED if using PEER_Join in peers)
    RoutingTable(IP_ADDRESS_ROW1B1, RS485_ADDRESS_ROW1SN, 0);
    RoutingTable(IP_ADDRESS_ROW2B1, RS485_ADDRESS_ROW2SN, 1);
    RoutingTable(IP_ADDRESS_BED1B1, RS485_ADDRESS_BED1SN, 2);
    RoutingTable(IP_ADDRESS_BED2B1, RS485_ADDRESS_BED2SN, 3);
```

All nodes are up and running since months..
OpenHAB server can access to all of them and operate all slots.

But SoulissApp seems to suffer from lazy network discovery and some node randomly have no slots.
By dropping the DB and re-creating it some of the working nodes become empty and some empty are filled with right slots.

Even trying to keep the phone active for about 5 minutes the discovery process do not fill all nodes.

Any idea ?

**Comment by plinioseniore** [comment]
Is this just a matter of building the DB, then once build things are
working properly? Have you tried to rebuild the DB without dropping it?

If so, is likely not a SoulissApp problem. Which souliss release are you
running on the Gateway?

Dario.

**Comment by ribico** [comment]
Yes, once the DB has been built.. everything is working fine.
Asking for node configuration without dropping the DB  add new slots.. and after some try you get the whole DB.. but it may require 2-4 times.

The GW (together with all the other boards) has been upgraded last time in August with the latest Souliss at that time.

Wouldn't be easier to have a sort of node discovery in the node view ?
When I see an empty node I could force typicals update for that instead of the whole network.

**Comment by shineangelic** [comment]
Yes, I have the same issue but I thought it was due to my sloppy network made of lazy chibis. Particularly, one of them is ALWAY answering late. If you have the same problem there must be something else.

I don't think this is a SoulissApp issue though, as every node replies indipendently and you would get errors if DB building procedure goes wrong, ie when two datagrams come in exactly same moment. The procedure was better when only the bridge node was answering. Since when we decoupled the DB struct, I observed this behaviour

**Comment by plinioseniore** [comment]
Actually is the Gateway that does a decoupling, because it request node by
node their typical and forward the information to SoulissApp. It does one
node per time with a timeout, so is quite slow.

We can keep things as are now, adding the feature to request a single node
from SoulissApp. Actually if you miss a node, you start  a new request
collecting again all data.

Isn't actually supported on the Gateway side, I will have a look. On the
SoulissApp side there should be an option at node level to request typical
for that node only, to be used only if someone has been missed.

**Comment by ribico** [comment]
wouldn't be possible to cache these information on the GW node ?

**Comment by plinioseniore** [comment]
In a network with 10 nodes will require 10% of the total RAM of an
ATmega328, is a waste.

Dario.

**Comment by ribico** [comment]
Ok, but isn't it already part of the persistence ?
I mean, since I have the persistence.. shouldn't I have also slots DB ?

**Comment by plinioseniore** [comment]
No, persistence stores only the output values and not the typical values
(that basically never change).

**Comment by shineangelic** [comment]
Maybe we could reach a compromise, as some nodes are really slow in answering, expecially when there are "holes" inbetween. What is the timeout now? Could we narrow it?

**Comment by plinioseniore** [comment]
Isn't easier to just allow the recall for typicals for a single node, to be
used in case?

**Comment by shineangelic** [comment]
not easier than narrowing a timeout. I would have to launch threads and timeouts. Consider that sometimes I don't even know what I will/shall receive

**Comment by plinioseniore** [comment]
You don't need to timeout, an option in the menu of the node to refresh
that node (sending out a single packet) will do the job. I will change the
Gateway to let it answer also for a single node.

This will be in any case an additional features, DB will be populated as is
now. As option the user could ask a refresh for a single node.

Looks fine?

**Comment by shineangelic** [comment]
I'm lost. What should I add? A refresh of the single node?

**Comment by plinioseniore** [comment]
Yes, an option in the menu (where there is Rename and others) to request
typical for that node, so that you can refresh a single node is has changed
or if data has been missed.

You send out the same request as is now, but you specify as StartOffset the
node ID that you would to refresh and as lenght 1, because you want that
node only.

**Comment by ribico** [comment]
this will be also useful when modifying a single node in the network.
you don't have to refresh the whole DB...

**Comment by shineangelic** [comment]
For me this is pointless. The issue was regarding the act of creating Database, when you are configuring SoulissApp. What would be the use of such an option apart from confusing the user? 

For me this should be managed "automatically", repeating the command or something...But adding another option to normal app operations is wrong. We already have the feature to refresh node

**Comment by plinioseniore** [comment]
Actually if you change one typical into one node, you have to refresh the
whole DB, because SoulissApp always request the whole set of data.

Actually there is yet a timeout with retry, but if you have tens of nodes
it may take very long time. So an update for a single node will help for
sure.

**Comment by juanpintom** [comment]
Im agree with you both :P An option to refresh just one node will be very
useful, Im working with an ESP node and Webconfiguration and everytime I
change something I need to refresh the whole DB :(

And we need to solve that "problem" with a big network, I noticed that when
one node isn't respond to the GW it try again a few times, could be
possible if a peer don't reply it takes too long to get all the network.

Regards

2015-10-01 17:21 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
Starting from commit efbfe43889, a request to rebuild a single node is available. The expected frame is the same as now, is enough the specify 1 as length and the ID of the node of interest.

As example, to request data for node with ID 3 the following frame is expected
0x22,0x0,0x0,0x3,0x1

**Comment by shineangelic** [comment]
node option "Rebuild Node" is now available

**Comment by juanpintom** [comment]
:O You are working so fast!  Ty both!

Regards :)
